<a href="https://colab.research.google.com/github/RITHWIK3224/GENERATIVE-AI-2025/blob/main/Generative_AL_2303A52423_week1_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
from math import sqrt
from sklearn.linear_model import LinearRegression


y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

In [ ]:
mae = mean_absolute_error(y_actual, y_pred)
print(f'Mean Absolute Error (MAE): {mae}')

Mean Absolute Error (MAE): 0.4600000000000016


In [ ]:
mse = mean_squared_error(y_actual, y_pred)
print(f'Mean Squared Error (MSE): {mse}')

Mean Squared Error (MSE): 0.24600000000000147


In [ ]:
rmse = sqrt(mse)
print(f'Root Mean Squared Error (RMSE): {rmse}')

Root Mean Squared Error (RMSE): 0.49598387070549127


In [ ]:
X = y_actual.reshape(-1, 1)
y = y_pred

In [ ]:
model = LinearRegression()
model.fit(X, y)


LinearRegression()

In [ ]:
print(f'Linear Regression Coefficients: {model.coef_}')
print(f'Linear Regression Intercept: {model.intercept_}')

Linear Regression Coefficients: [1.007]
Linear Regression Intercept: 0.17999999999999972


In [ ]:
y_pred_lr = model.predict(X)

In [ ]:
print(f'Predicted values using Linear Regression: {y_pred_lr}')

Predicted values using Linear Regression: [20.32 30.39 40.46 50.53 60.6 ]


In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [ ]:
y_actual = np.array([0, 0, 0, 0, 0])
y_pred = np.array([
    [0, 1, 1, 2, 0],
    [0, 1, 0, 2, 0],
    [1, 1, 2, 2, 1],
    [0, 2, 1, 0, 2],
    [2, 1, 2, 2, 2],
])


In [ ]:
y_actual_flat = np.repeat(y_actual, y_pred.shape[1])  # Repeat actual values for each prediction
y_pred_flat = y_pred.flatten()

In [ ]:
conf_matrix = confusion_matrix(y_actual_flat, y_pred_flat)

In [ ]:
# Evaluation Metrics
accuracy = accuracy_score(y_actual_flat, y_pred_flat)
precision = precision_score(y_actual_flat, y_pred_flat, average='macro')
recall = recall_score(y_actual_flat, y_pred_flat, average='macro')
f1 = f1_score(y_actual_flat, y_pred_flat, average='macro')

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
print("Confusion Matrix:")
print(conf_matrix)
print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")

Confusion Matrix:
[[ 7  8 10]
 [ 0  0  0]
 [ 0  0  0]]

Evaluation Metrics:
Accuracy: 0.28
Precision: 0.3333333333333333
Recall: 0.09333333333333334
F1-Score: 0.14583333333333334


In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2])

Metrics from scratch:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7000000000000001
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8

Metrics from libraries:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74     

In [ ]:
tp, fp, fn = {0: 0, 1: 0, 2: 0}, {0: 0, 1: 0, 2: 0}, {0: 0, 1: 0, 2: 0}
for i in range(len(Y_actual)):
    for cls in [0, 1, 2]:
        if Y_actual[i] == cls and Y_pred[i] == cls: tp[cls] += 1
        elif Y_actual[i] != cls and Y_pred[i] == cls: fp[cls] += 1
        elif Y_actual[i] == cls and Y_pred[i] != cls: fn[cls] += 1

In [ ]:

accuracy_scratch = np.sum(Y_actual == Y_pred) / len(Y_actual)
precision_scratch = {cls: tp[cls] / (tp[cls] + fp[cls]) for cls in [0, 1, 2]}
recall_scratch = {cls: tp[cls] / (tp[cls] + fn[cls]) for cls in [0, 1, 2]}
f1_scratch = {cls: 2 * precision_scratch[cls] * recall_scratch[cls] / (precision_scratch[cls] + recall_scratch[cls]) for cls in [0, 1, 2]}


In [ ]:
print("Metrics from scratch:")
print(f"Accuracy: {accuracy_scratch}")
for cls in [0, 1, 2]:
    print(f"Class {cls} - Precision: {precision_scratch[cls]}, Recall: {recall_scratch[cls]}, F1-Score: {f1_scratch[cls]}")


Metrics from scratch:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7000000000000001
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8


In [ ]:
accuracy_lib = accuracy_score(Y_actual, Y_pred)
precision_lib = precision_score(Y_actual, Y_pred, average=None)
recall_lib = recall_score(Y_actual, Y_pred, average=None)
f1_lib = f1_score(Y_actual, Y_pred, average=None)


In [ ]:
print("\nMetrics from libraries:")
print(f"Accuracy: {accuracy_lib}")
for cls, (p, r, f1) in enumerate(zip(precision_lib, recall_lib, f1_lib)):
    print(f"Class {cls} - Precision: {p}, Recall: {r}, F1-Score: {f1}")


Metrics from libraries:
Accuracy: 0.7333333333333333
Class 0 - Precision: 0.7777777777777778, Recall: 0.6363636363636364, F1-Score: 0.7
Class 1 - Precision: 0.7142857142857143, Recall: 0.625, F1-Score: 0.6666666666666666
Class 2 - Precision: 0.7142857142857143, Recall: 0.9090909090909091, F1-Score: 0.8


In [ ]:
print("\nClassification Report:")
print(classification_report(Y_actual, Y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74      0.73      0.73        30

